baseURL = "/"
languageCode = "en-us"
title = "oddgoo.com"
theme = "initio"
publishDir = "public"

[params]
    name = " "
    description = " "
    email = " "
    phone = " "
    address = " "
    year = 2018
    background = ""
    favicon = "/oddgoo_logo_square.png"
    DateForm = "January 2, 2006"

    footerEnableContact = false
    footerEnableFollowme = true
    footerEnableTextWidget = false
    footerEnableFormWidget = false

[[menu.main]]
    name = "home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "blog"
    url = "/post/"
    weight = 5

[params.disqus]
    site = "hugo-initio-site.disqus.com"

[params.sharethis]
    property = "123456789012345678901234"
    custom = true

[params.google.analytics]
    trackerID = "UA-47737540-2"

[[params.social]]
	title = "linkedin"
	url = "https://www.linkedin.com/in/cuauhtemoc-moreno-819a639/"
    icon = "fa-linkedin-square"
    footer = true
    sharethis = true
    network = "linkedin"
[[params.social]]
	title = "github"
	url = "https://github.com/oddgoo"
    icon = "fa-github"
    footer = true
    sharethis = false
    network = ""
[[params.social]]
	title = "email"
	url = "mailto:hello@oddgoo.com"
    icon = "fa-envelope"
    footer = true
    sharethis = true
    network = "email"
